# example kube yaml for the database. It is rather simple, as it is merely 2 services : the postgres, and the postgREST
apiVersion: v1
kind: Pod
metadata:
  name: cda-pg
  labels:
    app: cda-pg
spec:
  containers:
    - name: postgres
      image: cda-postgres

      env:
        - name: POSTGRES_PASSWORD
          value: secret

      volumeMounts:
      - name: source
        mountPath: /src
      - name: postgres-data
        mountPath: /var/lib/postgresql/data
      - name: postgres-config
        mountPath: /var/lib/postgresql/data/postgresql.conf


    - name: postgREST
      image: docker.io/postgrest/postgrest:v14.1

      env :
      - name: PGRST_DB_JWT_SECRET
        value: reallyreallyreallyreallyverysafe
      - name: PGRST_DB_JWT_SECRET_IS_BASE64
        value: "false"
      - name: PGRST_DB_URI
        value: postgres://postgres:secret@127.0.0.1:5432/cda

      ports:
      - containerPort: 3000
      - hostPort: 3000
      securityContext:
        runAsNonRoot: true
      
      volumeMounts:
      - name: postgrest-config
        mountPath: /postgrest/postgrest.conf
      
      args: ["/postgrest/postgrest.conf"]


  volumes: # todo
  - name: source
  - name: postgres-data
  - name: postgres-config
  - name: postgrest-config
